### ISSUE TITLE
GR6J correction

### ISSUE THREAD

**Issue by Dr-Jamie-Brown** [SimonDelmas/hydrogr#2]
Very well done creating this working GR package for python. 

I found a slight error in the GR6J.rs file whilst trying to compare hydrogr to the airgr R version. in line 116 the it should read exp_flow = x6*ar.exp(); and not exp_flow = x6/ar.exp(); . The issue creates extremely large flows when states[2]/x6 drops below -33 which in turn allows the exp_flow to become a extremely high. A simple error but has large modelling implications. 
![image](https://github.com/user-attachments/assets/b7e3711e-6a0e-4d91-83cf-32425ce4aae2)

**Comment by SimonDelmas** [comment]
Thank you very much for your feedback. I am currently traveling, but I will correct this when I return.

**Comment by SimonDelmas** [comment]
Fixed in version 1.2.1, thanks @Dr-Jamie-Brown !

**Comment by Dr-Jamie-Brown** [comment]
Thanks @SimonDelmas Very much appreciated
